# fly.toml app configuration file generated for agentur on 2025-07-29T17:58:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml
app            = "agentur"
primary_region = "fra"

[build]        # bleibt leer, weil Fly dein Dockerfile erkennt

[http_service]
  internal_port      = 3000        # MUSS dem Port aus server.js entsprechen
  auto_start_machines = true
  auto_stop_machines  = true       # 👉 nur `true`/`false`, nicht "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "256mb"               # reicht, spart $$ (≈ 0,73 $/Monat idle)
