app = "agentur"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[vm]]
  memory = "512MB"
  cpu_kind = "shared"
  cpus = 1
# fly.toml app configuration file generated for agentur-0qypda on 2025-08-17T08:48:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentur-0qypda'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'  # Für kontinuierliche WebSocket-Verbindungen
  auto_start_machines = true
  min_machines_running = 1    # Mindestens eine Instanz laufend halten
  processes = ['app']

# WebSocket Unterstützung
[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024  # Mehr RAM für Audio-Verarbeitung
